//CREATE USER
PUT http://localhost:3000/user
Content-Type: application/json

{
  "name": "s",
  "nickname": "d",
  "email": "te1ssste@gmail.com"
}

###

GET http://localhost:3000/user/1

###

POST http://localhost:3000/user/edit/1
Content-Type: application/json

{
  "nicknasme": "aaa"
}

###

PUT http://localhost:3000/task
Content-Type: application/json

{
  "title": "ss",
  "description": "teste",
  "limitDate": "26/03/2021",
  "status": "todo",
  "id_createdby": 1
}

### 

GET http://localhost:3000/tasks/